project:
  type: website
  output-dir: docs

website:
  favicon: /images/logo.png
  title: "OneGeochemistry"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Participate"
        file: participate.qmd
      - text: "Best Practices"
        file: best_practices.qmd
      - text: "Our Mission"
        file: our_mission.qmd
      - text: "Database Resilience"
        file: resilience.qmd
        

#resources:
#  - CNAME

# website:
#   favicon: /images/logo.png
#   title: "OneGeochemistry"
#   # navbar:
#   #   left:
#   #     # - href: index.qmd
#   #     #   text: Home
#   #     - publications.qmd
#   #     - about.qmd
#   sidebar:
#     style: "docked"
#     search: true
#     contents:
#       - text: "Welcome"
#         file: index.qmd
#       - section: "Participate"
#         contents:          
#           - get_engaged.qmd
#           - current activites.qmd
#       - best_practices.qmd
#       # section: "Best Practices"
#         # contents:
#          # - white papers.qmd
#          # - brown book.qmd
#       - about.qmd
#           # - faq.qmd
#   page-footer: "Copyright 2023, OneGeochemistry"
 
margin-header: |
  ![](/images/logo.png){width=50%}

format:
  html:
    theme: flatly #solar
#      light: flatly
#      dark: darkly
    css: styles.css
    toc: true 


