project:
  type: website
  output-dir: docs

website:
  favicon: /images/logo.png
  title: "OneGeochemistry"
  # navbar:
  #   left:
  #     # - href: index.qmd
  #     #   text: Home
  #     - publications.qmd
  #     - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - section: "Participate"
        contents:          
          - get_engaged.qmd
          - current activites.qmd
      - best_practices.qmd # section: "Best Practices"
        # contents:
         # - white papers.qmd
         # - brown book.qmd
      - section: 'About'
        contents:
          - onegeochemistry.qmd
          - publications.qmd
          - history.qmd
          # - faq.qmd
  page-footer: "Copyright 2023, OneGeochemistry"
 
margin-header: |
  ![](/images/logo.png){width=50%}

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true 


