---
title: 'Best Practices'
---
The format in which geochemical data are reported varies widely across the geochemistry community. However, a common format for all publications would greatly improve the (re)useability of research data, by ensuring that they are easily understood by others and allowing data quality to be objectively assessed.

A number of best practice recommendations have been produced for different aspects of geochemistry research, each proposing a structured format in which to publish research data.
The best practice documents compiled below are grouped by publications on **isotope ratio and chemical data** in general, **samples, rock type, chronology** and **paleoclimate**.

We encourage you to follow the relevant best practice from the list below to standardise your data and make them easily accessible, which can be crucial for successful future analysis and decision-making.

Additional resources:

- Best practice articles published by the AAG: <https://www.appliedgeochemists.org/best-practices>
- IAG Guide to the use of Metrological Terminology: <https://www.geoanalyst.org/glossary/>
- JCGM Guides in Metrology: <https://www.bipm.org/en/committees/jc/jcgm/publications>

</br>

::: {.callout-tip}
## Feedback Welcome
If you think we have missed something, please [get in touch](participate.qmd)!

Can't find a best practice appropriate for your data, but think there should be one? Consider getting involved in a OneGeochemistry [expert committee](participate.html#expert-committees) and produce a new best practice document.
:::


## General

::: {.callout-note appearance="simple" collapse="true"}
## Boone+ 2022. AusGeochem: An Open Platform for Geochemical Data Preservation, Dissemination and Synthesis.
To promote a more efficient and transparent geochemistry data ecosystem, a consortium of Australian university research laboratories called the AuScope Geochemistry Network assembled to build a collaborative platform for the express purpose of preserving, disseminating and collating geochronology and isotopic data. In partnership with geoscience-data-solutions company Lithodat Pty Ltd, the open, cloud-based AusGeochem platform (https://ausgeochem.auscope.org.au) was developed to simultaneously serve as a geosample registry, a geochemical data repository and a data analysis tool. Informed by method-specific groups of geochemistry experts and established international data reporting practices, community-agreed database schemas were developed for rock and mineral geosample metadata and secondary ion mass spectrometry U-Pb analysis, with additional models for laser ablation-inductively coupled-mass spectrometry U-Pb and Lu-Hf, Ar-Ar, fission-track and (U-Th-Sm)/He under development. Collectively, the AusGeochem platform provides the geochemistry community with a new, dynamic resource to help facilitate FAIR (Findable, Accessible, Interoperable, Reusable) data management, streamline data dissemination and advanced quantitative investigations of Earth system processes. By systematically archiving detailed geochemical (meta-)data in structured schemas, intractably large datasets comprising thousands of analyses produced by numerous laboratories can be readily interrogated in novel and powerful ways. These include rapid derivation of inter-data relationships, facilitating on-the-fly data compilation, analysis and visualisation.

Boone, S.C., Dalton, H., Prent, A., Kohlmann, F., Theile, M., Gréau, Y., Florin, G., Noble, W., Hodgekiss, S., Ware, B., Phillips, D., Kohn, B., O'Reilly, S., Gleadow, A., McInnes, B., Rawling, T., 2022. **AusGeochem: An Open Platform for Geochemical Data Preservation, Dissemination and Synthesis.** Geostandards and Geoanalytical Research 46, 245--25. <https://doi.org/10.1111/ggr.12419>
:::

:::{.callout-note appearance="simple" collapse="true"}
## Chamberlain+ 2021. Time to change the data culture in geochemistry.

Geochemical data are vital for understanding Earth’s past, present and future. However, currently only a fraction of geochemical data are findable, accessible, interoperable and reusable, limiting their use in the broadest range of scientific studies. There is an urgent need for international coordination of geochemical data and methods to unlock their full research potential.

Chamberlain, K. J., Lehnert, K. A., McIntosh, I. M., Morgan, D. J., & Wörner, G., 2021. **Time to change the data culture in geochemistry.** Nature Reviews Earth & Environment, 2(11), 737–739. <https://doi.org/10.1038/s43017-021-00237-w>
:::

:::{.callout-note appearance="simple" collapse="true"}
## Coplen 2011. Guidelines and recommended terms for expression of stable-isotope-ratio and gas-ratio measurement results.

To minimize confusion in the expression of measurement results of stable isotope and gas-ratio measurements, recommendations based on publications of the Commission on Isotopic Abundances and Atomic Weights of the International Union of Pure and Applied Chemistry (IUPAC) are presented. Whenever feasible, entries are consistent with the Système International d'Unités, the SI (known in English as the International System of Units), and the third edition of the International Vocabulary of Basic and General Terms in Metrology (VIM, 3rd edition). The recommendations presented herein are approved by the Commission on Isotopic Abundances and Atomic Weights and are designed to clarify expression of quantities related to measurement of isotope and gas ratios to ensure that quantity equations instead of numerical value equations are used for quantity definitions. Examples of column headings consistent with quantity calculus (also called the algebra of quantities) and examples of various deprecated usages connected with the terms recommended are presented.

Coplen, T.B., 2011. **Guidelines and recommended terms for expression of stable-isotope-ratio and gas-ratio measurement results.** Rapid Communications in Mass Spectrometry 25, 2538–2560. <https://doi.org/10.1002/rcm.5129>
:::


::: {.callout-note appearance="simple" collapse="true"}
## Deines+ 2003. Standards for publication of isotope ratio and chemical data in Chemical Geology.

In an International Journal such as Chemical Geology, it is vitally important to include a reasonable assessment of precision and accuracy, and appropriate information regarding analytical methodologies so that data can be compared between different laboratories. The policy of the Journal to insure adequate documentation is outlined below.

Deines, P., Goldstein, S.L., Oelkers, E.H., Rudnick, R.L., Walter, L.M., 2003. **Standards for publication of isotope ratio and chemical data in Chemical Geology.** Chemical Geology 202, 1--4. <https://doi.org/10.1016/j.chemgeo.2003.08.003>
:::

::: {.callout-note appearance="simple" collapse="true"}
## Demetriades+ 2022. International Union of Geological Sciences Manual of Standard Methods for Establishing the Global Geochemical Reference Network.

Demetriades, A., Johnson, C.C., Smith, D.B., Ladenberger, A., Adánez Sanjuan, P., Argyraki, A., Stouraiti, C., Caritat, P. de, Knights, K.V., Prieto Rincón, G., Simubali, G.N. (Editors), 2022. **International Union of Geological Sciences Manual of Standard Methods for Establishing the Global Geochemical Reference Network.** IUGS Commission on Global Geochemical Baselines, Athens, Hellenic Republic, Special Publication 2, 515 pp. Zenodo. <https://doi.org/10.5281/ZENODO.7307696>
:::

::: {.callout-note appearance="simple" collapse="true"}
## Goldstein+ 2014. Requirements for the Publication of Geochemical Data.

At their meeting during the 2008 American Geophysical Union, the Editors Roundtable agreed on a joint editorial policy statement that established a common set of standards for reporting geochemical data. The policy addresses the problem of inconsistency and incompleteness of data and metadata in publications, and helps to facilitate the incorporation of data into digital data collections.

Goldstein, S. L., Hofmann, A. W., Lehnert, K. A., 2014. **Requirements for the Publication of Geochemical Data.** Version 1.0. Interdisciplinary Earth Data Alliance (IEDA). <https://doi.org/10.1594/IEDA/100426>
:::

:::{.callout-note appearance="simple" collapse="true"}
## Peng+ 2022. Global Community Guidelines for Documenting, Sharing, and Reusing Quality Information of Individual Digital Datasets.

Open-source science builds on open and free resources that include data, metadata, software, and workflows. Informed decisions on whether and how to (re)use digital datasets are dependent on an understanding about the quality of the underpinning data and relevant information. However, quality information, being difficult to curate and often context specific, is currently not readily available for sharing within and across disciplines. To help address this challenge and promote the creation and (re)use of freely and openly shared information about the quality of individual datasets, members of several groups around the world have undertaken an effort to develop international community guidelines with practical recommendations for the Earth science community, collaborating with international domain experts. The guidelines were inspired by the guiding principles of being findable, accessible, interoperable, and reusable (FAIR). Use of the FAIR dataset quality information guidelines is intended to help stakeholders, such as scientific data centers, digital data repositories, and producers, publishers, stewards and managers of data, to: i) capture, describe, and represent quality information of their datasets in a manner that is consistent with the FAIR Guiding Principles; ii) allow for the maximum discovery, trust, sharing, and reuse of their datasets; and iii) enable international access to and integration of dataset quality information. This article describes the processes that developed the guidelines that are aligned with the FAIR principles, presents a generic quality assessment workflow, describes the guidelines for preparing and disseminating dataset quality information, and outlines a path forward to improve their disciplinary diversity.

Peng, G., Lacagnina, C., Downs, R.R., Ganske, A., Ramapriyan, H.K., Ivánová, I., Wyborn, L., Jones, D., Bastin, L., Shie, C., Moroni, D.F., 2022. **Global Community Guidelines for Documenting, Sharing, and Reusing Quality Information of Individual Digital Datasets.** Data Science Journal 21 (1), 8. <https://doi.org/10.5334/dsj-2022-008>
:::

:::{.callout-note appearance="simple" collapse="true"}
## Potts 2012. Glossary of Analytical and Metrological Terms from the International Vocabulary of Metrology (2008).

The Joint Committee for Guides in Metrology (JCGM) has introduced a revised third edition of the International Vocabulary of Metrology – basic and general concepts and associated terms (VIM: 2008) that replaces the second edition which was published in 1993. This article includes a table containing the terms and definitions that are most relevant to geoanalysis, designed to extend awareness and to promote best practice in the use of this terminology. Comparison is made, where appropriate, with definitions from the earlier 1993 definitions, to demonstrate the way in which thinking in metrological concepts has evolved over this time period.

Potts, P. J. (2012). Glossary of Analytical and Metrological Terms from the International Vocabulary of Metrology (2008). Geostandards and Geoanalytical Research 36(3) 231–246. <https://doi.org/10.1111/j.1751-908x.2011.00122.x>
:::


:::{.callout-note appearance="simple" collapse="true"}
## Staudigel+ 2003. Electronic data publication in geochemistry.

Many disciplines of geochemistry have no data reporting standards, and their use of metadata is inadequately developed. This presents problems to the quality of the published science, and it limits the utility of computers in data analysis and the exploitation of Information Technology (IT). We discuss problems of data and metadata publication, in particular for geochemistry, and offer solutions to these problems in the form of consistent data publication formats and a proposal for publication of metadata in geochemistry. Metadata are grouped according to types (location, sampling, characterization), and this grouping allows for the transfer of these formats to other Earth science disciplines. In a companion paper [Helly et al., 2003], we illustrate how these metadata groupings can be used in an IT context. Formats presented here are comprehensive and allow for modification and expansion. It is the hope of the authors that this paper initiates a constructive discussion of data formats and metadata in geochemistry. The most recent contributions to this discussion may be found at http:\\earthref.org\metadata\GERM\.

Staudigel, H., Helly, J., Koppers, A. A. P., Shaw, H. F., McDonough, W. F., Hofmann, A. W., Langmuir, C. H., Lehnert, K., Sarbas, B., Derry, L. A., & Zindler, A., 2003. **Electronic data publication in geochemistry.** Geochemistry, Geophysics, Geosystems, 4(3). <https://doi.org/10.1029/2002GC000314>
:::



## Samples
::: {.callout-note appearance="simple" collapse="true"}
## Damerow+ 2021. Sample Identifiers and Metadata to Support Data Management and Reuse in Multidisciplinary Ecosystem Sciences.

Physical samples are foundational entities for research across biological, Earth, and environmental sciences. Data generated from sample-based analyses are not only the basis of individual studies, but can also be integrated with other data to answer new and broader-scale questions. Ecosystem studies increasingly rely on multidisciplinary team-science to study climate and environmental changes. While there are widely adopted conventions within certain domains to describe sample data, these have gaps when applied in a multidisciplinary context. In this study, we reviewed existing practices for identifying, characterizing, and linking related environmental samples. We then tested practicalities of assigning persistent identifiers to samples, with standardized metadata, in a pilot field test involving eight United States Department of Energy projects. Participants collected a variety of sample types, with analyses conducted across multiple facilities. We address terminology gaps for multidisciplinary research and make recommendations for assigning identifiers and metadata that supports sample tracking, integration, and reuse. Our goal is to provide a practical approach to sample management, geared towards ecosystem scientists who contribute and reuse sample data.

Damerow, J.E., Varadharajan, C., Boye, K., Brodie, E.L., Burrus, M., Chadwick, K.D., Crystal-Ornelas, R., Elbashandy, H., Alves, R.J.E., Ely, K.S., Goldman, A.E., Haberman, T., Hendrix, V., Kakalia, Z., Kemner, K.M., Kersting, A.B., Merino, N., O'Brien, F., Perzan, Z., Robles, E., Sorensen, P., Stegen, J.C., Walls, R.L., Weisenhorn, P., Zavarin, M., Agarwal, D., 2021. **Sample Identifiers and Metadata to Support Data Management and Reuse in Multidisciplinary Ecosystem Sciences.** Data Science Journal 20 (1), 11. <https://doi.org/10.5334/dsj-2021-011>
:::


## Rock Type
::: {.callout-note appearance="simple" collapse="true"}
## Abbott+ 2022. Community Established Best Practice Recommendations for Tephra Studies-from Collection through Analysis.
Tephra is a unique volcanic product with an unparalleled role in understanding past eruptions, long-term behavior of volcanoes, and the effects of volcanism on climate and the environment. Tephra deposits also provide spatially widespread, extremely high-resolution time-stratigraphic markers across a range of sedimentary settings and are used in a range of disciplines (e.g., volcanology, climate science, archaeology, ecology, and impact assessment). Nonetheless, the study of tephra deposits is challenged by a lack of standardization that often inhibits data integration across geographic regions and across disciplines.
</br>
Here we present comprehensive recommendations for tephra data gathering and reporting that were developed by the tephra science community to serve as guidelines for future investigators and to ensure that sufficient data are gathered for transparency and interoperability.  Recommendations include standardized field and laboratory data collection along with reporting and correlation guidance. These are organized as tabulated lists of key metadata with their definition and purpose. They are system independent and usable for template, tool, and database development.  This new standardized framework promotes consistent tephra documentation and archiving, fosters interdisciplinary communication, and improves effectiveness of data sharing among diverse communities of researchers.  Wider adoption will help to expand the applicability and usability of tephra data and facilitate scientific collaboration and data reuse.

Abbott, P., Bonadonna, C., Bursik, M., Cashman, K., Davies, S., Jensen, B., Kuehn, S., Kurbatov, A., Lane, C., Plunkett, G., Smith, V., Thomlinson, E., Thordarsson, T., Walker, J.D., Wallace, K., 2022. **Community Established Best Practice Recommendations for Tephra Studies-from Collection through Analysis.** Zenodo. <https://doi.org/10.5281/zenodo.6568306>
:::

::: {.callout-note appearance="simple" collapse="true"}
## Case+ 2024. Guide and data requirements for submission of mineral deposit geochemical data in the Critical Minerals in Ores (CMiO) database.
This guide and template details data requirements for submission of mineral deposit geochemical data to the Critical Minerals in Ores (CMiO) database, hosted by Geoscience Australia, in partnership with the United States Geological Survey and the Geological Survey of Canada. The CMiO database is designed to capture multielement geochemical data from a wide variety of critical mineral-bearing deposits around the world. Samples included within this database must be well-characterized and come from localities that have been sufficiently studied to have a reasonable constraint on their deposit type and environment of formation. As such, only samples analysed by modern geochemical methods, and with certain minimum metadata attribution, can be accepted. Data that is submitted to the CMiO database will also be published via the Geoscience Australia Portal (portal.ga.gov.au) and Critical Minerals Mapping Initiative Portal (https://portal.ga.gov.au/persona/cmmi).

Case, G.N.D., Bastrakov, E.N., Graham, G.E., Hawkins, S.G., Hofstra, A.H., Huston, D.L., Lawley, C.J.M., Lisitsin, V.A., Wang, B. 2024. **Guide and data requirements for submission of mineral deposit geochemical data in the Critical Minerals in Ores (CMiO) database.** Record 2024/17. Geoscience Australia, Canberra. <https://dx.doi.org/10.26186/149408>
:::


::: {.callout-note appearance="simple" collapse="true"}
## Wallace+ 2022. Community established best practice recommendations for tephra studies---from collection through analysis.

Tephra is a unique volcanic product with an unparalleled role in understanding past eruptions, long-term behavior of volcanoes, and the effects of volcanism on climate and the environment. Tephra deposits also provide spatially widespread, high-resolution time-stratigraphic markers across a range of sedimentary settings and thus are used in numerous disciplines (e.g., volcanology, climate science, archaeology). Nonetheless, the study of tephra deposits is challenged by a lack of standardization that inhibits data integration across geographic regions and disciplines. We present comprehensive recommendations for tephra data gathering and reporting that were developed by the tephra science community to guide future investigators and to ensure that sufficient data are gathered for interoperability. Recommendations include standardized field and laboratory data collection, reporting and correlation guidance. These are organized as tabulated lists of key metadata with their definition and purpose. They are system independent and usable for template, tool, and database development. This standardized framework promotes consistent documentation and archiving, fosters interdisciplinary communication, and improves effectiveness of data sharing among diverse communities of researchers.

Wallace, K.L., Bursik, M.I., Kuehn, S., Kurbatov, A.V., Abbott, P., Bonadonna, C., Cashman, K., Davies, S.M., Jensen, B., Lane, C., Plunkett, G., Smith, V.C., Tomlinson, E., Thordarsson, T., Walker, J.D., 2022. **Community established best practice recommendations for tephra studies---from collection through analysis.** Scientific Data 9, 1--11. <https://doi.org/10.1038/s41597-022-01515-y>
:::


## Chronology
::: {.callout-note appearance="simple" collapse="true"}
## Boone+ 2023. Supplementary Information 1: A geospatial platform for the tectonic interpretation of low-temperature thermochronology Big Data.
To promote a more efficient and transparent geochemistry data ecosystem, a consortium of Australian university research laboratories called the AuScope Geochemistry Network assembled to build a collaborative platform for the express purpose of preserving, disseminating and collating geochronology and isotopic data. In partnership with geoscience-data-solutions company Lithodat Pty Ltd, the open, cloud-based AusGeochem platform (https://ausgeochem.auscope.org.au) was developed to simultaneously serve as a geosample registry, a geochemical data repository and a data analysis tool. Informed by method-specific groups of geochemistry experts and established international data reporting practices, community-agreed database schemas were developed for rock and mineral geosample metadata and secondary ion mass spectrometry U-Pb analysis, with additional models for laser ablation-inductively coupled-mass spectrometry U-Pb and Lu-Hf, Ar-Ar, fission-track and (U-Th-Sm)/He under development. Collectively, the AusGeochem platform provides the geochemistry community with a new, dynamic resource to help facilitate FAIR (Findable, Accessible, Interoperable, Reusable) data management, streamline data dissemination and advanced quantitative investigations of Earth system processes. By systematically archiving detailed geochemical (meta-)data in structured schemas, intractably large datasets comprising thousands of analyses produced by numerous laboratories can be readily interrogated in novel and powerful ways. These include rapid derivation of inter-data relationships, facilitating on-the-fly data compilation, analysis and visualisation.
Presented in Supplementary Information 1 are the fission track and (U-Th)/He datatables for AusGeochem, including data type and unit specifications, and field descriptions.

Boone, S.C., Kohlmann, F., Noble, W. et al., 2023. **A geospatial platform for the tectonic interpretation of low-temperature thermochronology Big Data.** Sci Rep 13, 8581. <https://doi.org/10.1038/s41598-023-35776-3>
:::

::: {.callout-note appearance="simple" collapse="true"}
## Condon+ 2024. Recommendations for the reporting and interpretation of isotope dilution U-Pb geochronological information.

U-Pb geochronology by isotope dilution−thermal ionization mass spectrometry (ID-TIMS) has the potential to be the most precise and accurate of the deep time chronometers, especially when applied to high-U minerals such as zircon. Continued analytical improvements have made this technique capable of regularly achieving better than 0.1% precision and accuracy of dates from commonly occurring high-U minerals across a wide range of geological ages and settings. To help maximize the long-term utility of published results, we present and discuss some recommendations for reporting ID-TIMS U-Pb geochronological data and associated metadata in accordance with accepted principles of data management. Further, given that the accuracy of reported ages typically depends on the interpretation applied to a set of individual dates, we discuss strategies for data interpretation. We anticipate that this paper will serve as an instructive guide for geologists who are publishing ID-TIMS U-Pb data, for laboratories generating the data, the wider geoscience community who use such data, and also editors of journals who wish to be informed about community standards. Combined, our recommendations should increase the utility, veracity, versatility, and “half-life” of ID-TIMS U-Pb geochronological data.

Condon, D., Schoene, B., Schmitz, M., Schaltegger, U., Ickert, R. B., Amelin, Y., Augland, L. E., Chamberlain, K. R., Coleman, D. S., Connelly, J. N., Corfu, F., Crowley, J. L., Davies, J. H. F. L., Denyszyn, S. W., Eddy, M. P., Gaynor, S. P., Heaman, L. M., Huyskens, M. H., Kamo, S., Kasbohm, J., Keller, C.B., MacLennan, S.A., McLean, N.M., Noble, S., Ovtcharova, M., Paul, A., Ramezani, J., Rioux, M., Sahy, D., Scoates, J.S., Szymanowski, D., Tapster, S., Tichomirowa, M., Wall, C.J., Wotzlaw, J.-F., Yang, C., Yin, Q.-Z, 2024. **Recommendations for the reporting and interpretation of isotope dilution U-Pb geochronological information.** GSA Bulletin. <https://doi.org/10.1130/B37321.1>
:::

::: {.callout-note appearance="simple" collapse="true"}
## Courtney Mustaphi+ 2019. Guidelines for reporting and archiving 210Pb sediment chronologies to improve fidelity and extend data lifecycle.

Radiometric dating methods are essential for developing geochronologies to study Late Quaternary environmental change and 210Pb dating is commonly used to produce age-depth models from recent (within 150 years) sediments and other geoarchives. The past two centuries are marked by rapid environmental socio-ecological changes frequently attributed to anthropogenic land-use activities, modified biogeochemical cycles, and climate change. Consequently, historical reconstructions over this recent time interval have high societal value because analyses of these datasets provide understanding of the consequences of environmental modifications, critical ecosystem thresholds, and to define desirable ranges of variation for management, restoration, and conservation. For this information to be used more broadly, for example to support land management decisions or to contribute data to regional analyses of ecosystem change, authors must report all of the useful age-depth model information. However, at present there are no guidelines for researchers on what information should be reported to ensure 210Pb data are fully disclosed, reproducible, and reusable; leading to a plethora of reporting styles, including inadequate reporting that reduces potential reusability and shortening the data lifecycle. For example, 64% of the publications in a literature review of 210Pb dated geoarchives did not include any presentation of age uncertainty estimates in modeled calendar ages used in age-depth models. Insufficient reporting of methods and results used in 210Pb dating geoarchives severely hampers reproducibility and data reusability, especially in analyses that make use of databased palaeoenvironmental data. Reproducibility of data is fundamental to further analyses of the number of palaeoenvironmental data and the spatial coverage of published geoarchives sites. We suggest, and justify, a set of minimum reporting guidelines for metadata and data reporting for 210Pb dates, including an IEDA (Interdisciplinary Earth Data Alliance), LiPD (Linked Paleo Data) and generic format data presentation templates, to contribute to improvements in data archiving standards and to facilitate the data requirements of researchers analyzing datasets of several palaeoenvironmental study sites. We analyse practices of methods, results and first order interpretation of 210Pb data and make recommendations to authors on effective data reporting and archiving to maximize the value of datasets. We provide empirical evidence from publications and practitioners to support our suggested reporting guidelines. These guidelines increase the scientific value of 210Pb by expanding its relevance in the data lifecycle. Improving quality and fidelity of environmental datasets broadens interdisciplinary use, lengthens the potential lifecycle of data products, and achieves requirements applicable for evidenced-based policy support.

Courtney Mustaphi, C.J., Brahney, J., Aquino-López, M.A., Goring, S., Orton, K., Noronha, A., Czaplewski, J., Asena, Q., Paton, S., Panga Brushworth, J., 2019. **Guidelines for reporting and archiving 210Pb sediment chronologies to improve fidelity and extend data lifecycle.** Quaternary Geochronology 52, 77--87. <https://doi.org/10.1016/j.quageo.2019.04.003>
:::

::: {.callout-note appearance="simple" collapse="true"}
## Dutton+ 2017. Data reporting standards for publication of U-series data for geochronology and timescale assessment in the earth sciences.

Uranium-series data provide essential dating and tracer tools for a broad spectrum of geologic processes. Data reported in U-series geochronology studies often contain insufficient information to completely assess the data collected. It is frequently not possible to calculate a date using the information provided or to re-calculate using different parameters, ultimately limiting the value of the data. The decay constants used are particularly important in that some of the relevant U-series isotopes have been revised. Here we provide a rationale for a minimum set of required data that will enable most calculations and facilitate later data comparisons. Along with these data reporting norms, we discuss additional metadata that will improve understanding of the data and also enhance the ability to re-interpret and assess them in the context of other studies. We posit that these recommendations will provide a foundation for increasing the longevity and usefulness of measurements in the discipline of U-series geochronology.

Dutton, A., Rubin, K., McLean, N., Bowring, J., Bard, E., Edwards, R.L., Henderson, G.M., Reid, M.R., Richards, D.A., Sims, K.W.W., Walker, J.D., Yokoyama, Y., 2017. **Data reporting standards for publication of U-series data for geochronology and timescale assessment in the earth sciences.** Quaternary Geochronology 39, 142-149. <https://doi.org/10.1016/j.quageo.2017.03.001>
:::

::: {.callout-note appearance="simple" collapse="true"}
## Flowers+ 2022. (U-Th)/He chronology: Part 1. Data, uncertainty, and reporting.

The field of (U-Th)/He geochronology and thermochronology has grown enormously over the past ∼25 years. The tool is applicable across much of geologic time, new (U-Th)/He chronometers are under continuous development, and the method is used in a diverse array of studies. Consequently, the technique has a rapidly expanding user base, and new labs are being established worldwide. This presents both opportunities and challenges. Currently there are no universally agreedupon protocols for reporting measured (U-Th)/He data or data derivatives. Nor are there standardized practices for reporting He diffusion kinetic, 4He/3He, or continuous ramped heating data. Approaches for reporting uncertainties associated with all types of data also vary widely. Here, we address these issues. We review the fundamentals of the methods, the types of materials that can be dated, how data are acquired, the process and choices associated with data reduction, and make recommendations for data and uncertainty reporting. We advocate that both the primary measured and derived data be reported, along with statements of assumptions, appropriate references, and clear descriptions of the methods used to compute derived data from measured values. The adoption of more comprehensive and uniform approaches to data and uncertainty reporting will enable data to be re-reduced in the future with different interpretative contexts and data reduction methods, and will facilitate inter-comparison of data sets generated by different laboratories. Together, this will enhance the value, cross-disciplinary use, reliability, and ongoing development of (U-Th)/He chronology.

Flowers, R.M., Zeitler, P.K., Danišík, M., Reiners, P.W., Gautheron, C., Ketcham, R.A., Metcalf, J.R., Stockli, D.F., Enkelmann, E., Brown, R.W., 2022. **(U-Th)/He chronology: Part 1. Data, uncertainty, and reporting.** GSA Bulletin 135 (1-2), 104--136. <https://doi.org/10.1130/b36266.1>
:::

::: {.callout-note appearance="simple" collapse="true"}
## Flowers+ 2022. (U-Th)/He chronology: Part 2. Considerations for evaluating, integrating, and interpreting conventional individual aliquot data.

The (U-Th)/He dating technique is an essential tool in Earth science research with diverse thermochronologic, geochronologic, and detrital applications. It is now used in a wide range of tectonic, structural, petrological, sedimentary, geomorphic, volcanological, and planetary studies. While in some circumstances the interpretation of (U-Th)/He data is relatively straightforward, in other cases it is less so. In some geologic contexts, individual analyses of the same mineral from a single sample are expected to yield dates that differ well beyond their analytical uncertainty owing to variable He diffusion kinetics. Although much potential exists to exploit this phenomenon to decipher more detailed thermal history information, distinguishing interpretable intra-sample data variation caused by kinetic differences between crystals from uninterpretable overdispersion caused by other factors can be challenging. Nor is it always simple to determine under what circumstances it is appropriate to integrate multiple individual analyses using a summary statistic such as a mean sample date or to decide on the best approach for incorporating data into the interpretive process of thermal history modeling. Here we offer some suggestions for evaluating data, attempt to summarize the current state of thinking on the statistical characterization of data sets, and describe the practical choices (e.g., model structure, path complexity, data input, weighting of different geologic and chronologic information) that must be made when setting up thermal history models. We emphasize that there are no hard and fast rules in any of these realms, which continue to be an important focus of improvement and community discussion, and no single interpretational and modeling philosophy should be forced on data sets. The guiding principle behind all suggestions made here is for transparency in reporting the steps and assumptions associated with evaluating, integrating, and interpreting data, which will promote the continued development of (U-Th)/He chronology.

Flowers, R. M., Ketcham, R. A., Enkelmann, E., Gautheron, C., Reiners, P. W., Metcalf, J. R., Danišík, M., Stockli, D. F., & Brown, R. W. (2022). **(U-Th)/He chronology: Part 2. Considerations for evaluating, integrating, and interpreting conventional individual aliquot data.** GSA Bulletin 135 (1–2), 137–161. <https://doi.org/10.1130/b36268.1>
:::


::: {.callout-note appearance="simple" collapse="true"}
## Horstwood+ 2016. Community‐Derived Standards for LA‐ICP‐MS U‐(Th‐)Pb Geochronology -- Uncertainty Propagation, Age Interpretation and Data Reporting.

The LA-ICP-MS U-(Th-)Pb geochronology international community has defined new standards for the determination of U-(Th-)Pb ages. A new workflow defines the appropriate propagation of uncertainties for these data, identifying random and systematic components. Only data with uncertainties relating to random error should be used in weighted mean calculations of population ages; uncertainty components for systematic errors are propagated after this stage, preventing their erroneous reduction. Following this improved uncertainty propagation protocol, data can be compared at different uncertainty levels to better resolve age differences. New reference values for commonly used zircon, monazite and titanite reference materials are defined (based on ID-TIMS) after removing corrections for common lead and the effects of excess 230Th. These values more accurately reflect the material sampled during the determination of calibration factors by LA-ICP-MS analysis. Recommendations are made to graphically represent data only with uncertainty ellipses at 2s and to submit or cite validation data with sample data when submitting data for publication. New data-reporting standards are defined to help improve the peer-review process. With these improvements, LA-ICP-MS U-(Th-)Pb data can be considered more robust, accurate, better documented and quantified, directly contributing to their improved scientific interpretation.

Horstwood, M.S.A., Košler, J., Gehrels, G., Jackson, S.E., McLean, N.M., Paton, C., Pearson, N.J., Sircombe, K., Sylvester, P., Vermeesch, P., Bowring, J.F., Condon, D.J., Schoene, B., 2016. **Community‐Derived Standards for LA‐ICP‐MS U‐(Th‐)Pb Geochronology -- Uncertainty Propagation, Age Interpretation and Data Reporting.** Geostandards and Geoanalytical Research 40, 311--332. <https://doi.org/10.1111/j.1751-908x.2016.00379.x>
:::

::: {.callout-note appearance="simple" collapse="true"}
## Klein+Eddy 2023. What’s in an age? Calculation and interpretation of ages and durations from U-Pb zircon geochronology of igneous rocks.

Accurate assessment of the duration of zircon crystallization within igneous rocks is critical for constraining the time scales of magmatic evolution and storage, which have important implications for our understanding of magmatic fluxes and volcanic hazards. However, estimation of crystallization durations from finite geochronologic data sets is difficult and typically relies on numerous implicit assumptions. In this contribution, we evaluate these assumptions and provide recommendations for better interpretation of crystallization durations from individual samples by developing a simplified theoretical framework to relate zircon growth, nucleation, and armoring rates to zircon ages. We first investigate single zircon analyses and show that ages produced with methods that integrate the entire grain or grain fragments (e.g., chemical abrasion–isotope dilution–thermal ionization mass spectrometry [CA-ID-TIMS]) are inevitably biased toward the second half of the zircon growth interval, while subsampling of grains via microbeam approaches will only capture the majority of the zircon crystallization duration when the microbeam spot size is less than ~25% of the zircon minor axis, and the analytical uncertainty of the measurement is less than ~20% of the duration over which the individual zircon grew.
</br>
We subsequently investigate the distribution of zircon mean ages produced through various combinations of zircon growth rate, nucleation rate, and the probability of zircon being armored by major phases. We show that zircon age distributions cannot be directly predicted from the rate of zircon mass crystallized, as many combinations of growth, nucleation, and armoring rates result in distinct age distributions, yet they produce nearly identical mass crystallization rates. Finally, we develop two equations that can be used to constrain the duration of crystallization observed within individual samples. In scenarios where the observed age dispersion is consistent with the reported analytical uncertainties, the first equation can be used to estimate the maximum duration. Otherwise, when the measured zircon population is overdispersed, a second equation constrains the minimum duration of zircon crystallization.

Klein, B. Z., & Eddy, M. P., 2023. **What’s in an age? Calculation and interpretation of ages and durations from U-Pb zircon geochronology of igneous rocks.** GSA Bulletin, 136 (1-2), 93–109. <https://doi.org/10.1130/b36686.1>
:::


::: {.callout-note appearance="simple" collapse="true"}
## Kohn+ 2024. Interpreting and reporting fission-track chronological data.

Fission-track dating is based on the analysis of tracks—linear damage trails—produced by the spontaneous fission of 238U in a range of natural accessory minerals and glasses. The retention of tracks is sensitive to elevated temperatures, and the data serve principally as a tool for recording thermal histories of rocks, potentially over the range of ∼20−350 °C, depending on the specific minerals studied. As such, in most cases, fission-track data generally bear little or no direct relationship to the original formation age of the material studied. The age range of fission-track dating is related to the product of age and uranium content, and ages from several tens of years to older than 1 Ga are reported. Fission-track analysis led to the development of powerful modeling techniques. When used with appropriate geological constraints, these modeling techniques allow important geological processes to be addressed in a broad range of upper crustal settings.
</br>
Since early attempts to standardize the treatment of fission-track data and system calibration over more than 30 years ago, major advancements were made in the methodology, necessitating the development of new, updated data reporting requirements. Inconsistencies in reporting impede public data transparency, accessibility and reuse, Big Data regional syntheses, and interlaboratory analytical comparisons.
</br>
This paper briefly reviews the fundamentals of fission-track dating and applications to provide context for recommended guidelines for reporting and supporting essential meta fission-track data for publication and methodological archiving in structured formats that conform with FAIR (Findable, Accessible, Interoperable, and Reusable) data principles. Adopting such practices will ensure that data can be readily accessed, interrogated, and reused, allowing for further integration with other numerical geoscience techniques.

Kohn, B. P., Ketcham, R. A., Vermeesch, P., Boone, S. C., Hasebe, N., Chew, D., Bernet, M., Chung, L., Danišík, M., Gleadow, A. J. W., & Sobel, E. R., 2024. **Interpreting and reporting fission-track chronological data.** GSA Bulletin. <https://doi.org/10.1130/b37245.1>
:::

::: {.callout-note appearance="simple" collapse="true"}
## Mahan+ 2022. Guide for interpreting and reporting luminescence dating results.

The development and application of luminescence dating and dosimetry techniques have grown exponentially in the last several decades. Luminescence methods provide age control for a broad range of geological and archaeological contexts and can characterize mineral and glass properties linked to geologic origin, Earth-surface processes, and past exposure to light, heat, and ionizing radiation. The applicable age range for luminescence methods spans the last 500,000 years or more, which covers the period of modern human evolution, and provides context for rates and magnitudes of geological processes, hazards, and climate change. Given the growth in applications and publications of luminescence data, there is a need for unified, community-driven guidance regarding the publication and interpretation of luminescence results.
</br>
This paper presents a guide to the essential information necessary for publishing and archiving luminescence ages as well as supporting data that is transportable and expandable for different research objectives and publication outlets. We outline the information needed for the interpretation of luminescence data sets, including data associated with equivalent dose, dose rate, age models, and stratigraphic context. A brief review of the fundamentals of luminescence techniques and applications, including guidance on sample collection and insight into laboratory processing and analysis steps, is presented to provide context for publishing and data archiving.

Mahan, S. A., Rittenour, T. M., Nelson, M. S., Ataee, N., Brown, N., DeWitt, R., Durcan, J., Evans, M., Feathers, J., Frouin, M., Guérin, G., Heydari, M., Huot, S., Jain, M., Keen-Zebert, A., Li, B., López, G. I., Neudorf, C., Porat, N., Rodrigues, K., Oliveira Sawakuchi, A., Spencer, J.Q.G., & Thomsen, K. (2022). **Guide for interpreting and reporting luminescence dating results.** GSA Bulletin 135 (5–6), 1580-1502. <https://doi.org/10.1130/b36404.1>
:::

::: {.callout-note appearance="simple" collapse="true"}
## Schaen+ 2020. Interpreting and reporting 40Ar/39Ar geochronologic data.

The 40Ar/39Ar dating method is among the most versatile of geochronometers, having the potential to date a broad variety of K-bearing materials spanning from the time of Earth’s formation into the historical realm. Measurements using modern noble-gas mass spectrometers are now producing 40Ar/39Ar dates with analytical uncertainties of ∼0.1%, thereby providing precise time constraints for a wide range of geologic and extraterrestrial processes. Analyses of increasingly smaller subsamples have revealed age dispersion in many materials, including some minerals used as neutron fluence monitors. Accordingly, interpretive strategies are evolving to address observed dispersion in dates from a single sample. Moreover, inferring a geologically meaningful “age” from a measured “date” or set of dates is dependent on the geological problem being addressed and the salient assumptions associated with each set of data. We highlight requirements for collateral information that will better constrain the interpretation of 40Ar/39Ar data sets, including those associated with single-crystal fusion analyses, incremental heating experiments, and in situ analyses of microsampled domains. To ensure the utility and viability of published results, we emphasize previous recommendations for reporting 40Ar/39Ar data and the related essential metadata, with the amendment that data conform to evolving standards of being findable, accessible, interoperable, and reusable (FAIR) by both humans and computers. Our examples provide guidance for the presentation and interpretation of 40Ar/39Ar dates to maximize their interdisciplinary usage, reproducibility, and longevity.

Schaen, A.J., Jicha, B.R., Hodges, K.V., Vermeesch, P., Stelten, M.E., Mercer, C.M., Phillips, D., Rivera, T.A., Jourdan, F., Matchan, E.L., Hemming, S.R., Morgan, L.E., Kelley, S.P., Cassata, W.S., Heizler, M.T., Vasconcelos, P.M., Benowitz, J.A., Koppers, A.A.P., Mark, D.F., Niespolo, E.M., Sprain, C.J., Hames, W.E., Kuiper, K.F., Turrin, B.D., Renne, P.R., Ross, J., Nomade, S., Guillou, H., Webb, L.E., Cohen, B.A., Calvert, A.T., Joyce, N., Ganerød, M., Wijbrans, J., Ishizuka, O., He, H., Ramirez, A., Pfänder, J.A., Lopez-Martínez, M., Qiu, H., Singer, B.S., 2020. **Interpreting and reporting 40Ar/39Ar geochronologic data.** GSA Bulletin 133 (3--4), 461--487. <https://doi.org/10.1130/b35560.1>
:::

::: {.callout-note appearance="simple" collapse="true"}
## Walker+ 2008. Geochron Workshop reports sponsored by EarthChem and EARTHTIME.

Walker, D.J., Condon, D., Thompson, W., Renne, P., Koppers, A., Hodges, K., Reiners, P., Stockli, D., Schmitz, M., Bowring, S., Gehrels, G., 2008. **Geochron Workshop reports sponsored by EarthChem and EARTHTIME.** Zenodo. <https://doi.org/10.5281/ZENODO.4313859>
:::


## Low-T Geochemistry
::: {.callout-note appearance="simple" collapse="true"}
## Bertrand+ 2024. Inorganic geochemistry of lake sediments: A review of analytical techniques and guidelines for data interpretation.
Inorganic geochemistry is a powerful tool in paleolimnology. It has become one of the most commonly used techniques to analyze lake sediments, particularly due to the development and increasing availability of XRF core scanners during the last two decades. It allows for the reconstruction of the continuous processes that occur in lakes and their watersheds, and it is ideally suited to identify event deposits. How earth surface processes and limnological conditions are recorded in the inorganic geochemical composition of lake sediments is, however, relatively complex. Here, we review the main techniques used for the inorganic geochemical analysis of lake sediments and we offer guidance on sample preparation and instrument selection. We then summarize the best practices to process and interpret bulk inorganic geochemical data. In particular, we emphasize that log-ratio transformation is critical for the rigorous statistical analysis of geochemical datasets, whether they are obtained by XRF core scanning or more traditional techniques. In addition, we show that accurately interpreting inorganic geochemical data requires a sound understanding of the main components of the sediment (organic matter, biogenic silica, carbonates, lithogenic particles) and mineral assemblages. Finally, we provide a series of examples illustrating the potential and limits of inorganic geochemistry in paleolimnology. Although the examples presented in this paper focus on lake and fjord sediments, the principles presented here also apply to other sedimentary environments.

Bertrand, S., Tjallingii, R., Kylander, M. E., Wilhelm, B., Roberts, S. J., Arnaud, F., Brown, E., & Bindler, R., 2024. **Inorganic geochemistry of lake sediments: A review of analytical techniques and guidelines for data interpretation.** Earth-Science Reviews 249, 104639. <https://doi.org/10.1016/j.earscirev.2023.104639>
:::

::: {.callout-note appearance="simple" collapse="true"}
## Brantley+ 2021. The future low-temperature geochemical data-scape as envisioned by the U.S. geochemical community.
Data sharing benefits the researcher, the scientific community, and the public by allowing the impact of data to be generalized beyond one project and by making science more transparent. However, many scientific communities have not developed protocols or standards for publishing, citing, and versioning datasets. One community that lags in data management is that of low-temperature geochemistry (LTG). This paper resulted from an initiative from 2018 through 2020 to convene LTG and data scientists in the U.S. to strategize future management of LTG data. Through webinars, a workshop, a preprint, a townhall, and a community survey, the group of U.S. scientists discussed the landscape of data management for LTG – the data-scape. Currently this data-scape includes a “street bazaar” of data repositories. This was deemed appropriate in the same way that LTG scientists publish articles in many journals. The variety of data repositories and journals reflect that LTG scientists target many different scientific questions, produce data with extremely different structures and volumes, and utilize copious and complex metadata. Nonetheless, the group agreed that publication of LTG science must be accompanied by sharing of data in publicly accessible repositories, and, for sample-based data, registration of samples with globally unique persistent identifiers. LTG scientists should use certified data repositories that are either highly structured databases designed for specialized types of data, or unstructured generalized data systems. Recognizing the need for tools to enable search and cross-referencing across the proliferating data repositories, the group proposed that the overall data informatics paradigm in LTG should shift from “build data repository, data will come” to “publish data online, cybertools will find”. Funding agencies could also provide portals for LTG scientists to register funded projects and datasets, and forge approaches that cross national boundaries. The needed transformation of the LTG data culture requires emphasis in student education on science and management of data.

Brantley, S.L., Wen, T., Agarwal, D.A., Catalano, J.G., Schroeder, P.A., Lehnert, K., Varadharajan, C., Pett-Ridge, J., Engle, M., Castronova, A.M., Hooper, R.P., Ma, X., Jin, L., McHenry, K., Aronson, E., Shaughnessy, A.R., Derry, L.A., Richardson, J., Bales, J., Pierce, E.M., 2021. **The future low-temperature geochemical data-scape as envisioned by the U.S. geochemical community.** Computers & Geosciences 157, 104933. <https://doi.org/10.1016/j.cageo.2021.104933>
:::

::: {.callout-note appearance="simple" collapse="true"}
## Demetriades+ 2020. International Union of Geological Sciences Manual of Standard Geochemical Methods for the Global Black Soil Project.

Demetriades, A., Huimin, D., Kai, L., Savin, I., Birke, M., Johnson, C.C., Argyraki, A., 2020. **International Union of Geological Sciences Manual of Standard Geochemical Methods for the Global Black Soil Project.** <https://doi.org/10.5281/ZENODO.7267967>
:::


## Paleoclimate
::: {.callout-note appearance="simple" collapse="true"}
## Khider+ 2019. PaCTS 1.0: A Crowdsourced Reporting Standard for Paleoclimate Data.

The progress of science is tied to the standardization of measurements, instruments, and data. This is especially true in the Big Data age, where analyzing large data volumes critically hinges on the data being standardized. Accordingly, the lack of community-sanctioned data standards in paleoclimatology has largely precluded the benefits of Big Data advances in the field. Building upon recent efforts to standardize the format and terminology of paleoclimate data, this article describes the Paleoclimate Community reporTing Standard (PaCTS), a crowdsourced reporting standard for such data. PaCTS captures which information should be included when reporting paleoclimate data, with the goal of maximizing the reuse value of paleoclimate data sets, particularly for synthesis work and comparison to climate model simulations. Initiated by the LinkedEarth project, the process to elicit a reporting standard involved an international workshop in 2016, various forms of digital community engagement over the next few years, and grassroots working groups. Participants in this process identified important properties across paleoclimate archives, in addition to the reporting of uncertainties and chronologies; they also identified archive-specific properties and distinguished reporting standards for new versus legacy data sets. This work shows that at least 135 respondents overwhelmingly support a drastic increase in the amount of metadata accompanying paleoclimate data sets. Since such goals are at odds with present practices, we discuss a transparent path toward implementing or revising these recommendations in the near future, using both bottom-up and top-down approaches.

Khider, D., Emile‐Geay, J., McKay, N.P., Gil, Y., Garijo, D., Ratnakar, V., Alonso‐Garcia, M., Bertrand, S., Bothe, O., Brewer, P., Bunn, A., Chevalier, M., Comas‐Bru, L., Csank, A., Dassié, E., DeLong, K., Felis, T., Francus, P., Frappier, A., Gray, W., Goring, S., Jonkers, L., Kahle, M., Kaufman, D., Kehrwald, N.M., Martrat, B., McGregor, H., Richey, J., Schmittner, A., Scroxton, N., Sutherland, E., Thirumalai, K., Allen, K., Arnaud, F., Axford, Y., Barrows, T., Bazin, L., Pilaar Birch, S.E., Bradley, E., Bregy, J., Capron, E., Cartapanis, O., Chiang, H. ‐W., Cobb, K.M., Debret, M., Dommain, R., Du, J., Dyez, K., Emerick, S., Erb, M.P., Falster, G., Finsinger, W., Fortier, D., Gauthier, N., George, S., Grimm, E., Hertzberg, J., Hibbert, F., Hillman, A., Hobbs, W., Huber, M., Hughes, A.L.C., Jaccard, S., Ruan, J., Kienast, M., Konecky, B., Le Roux, G., Lyubchich, V., Novello, V.F., Olaka, L., Partin, J.W., Pearce, C., Phipps, S.J., Pignol, C., Piotrowska, N., Poli, M. ‐S., Prokopenko, A., Schwanck, F., Stepanek, C., Swann, G.E.A., Telford, R., Thomas, E., Thomas, Z., Truebe, S., Gunten, L., Waite, A., Weitzel, N., Wilhelm, B., Williams, J., Williams, J.J., Winstrup, M., Zhao, N., Zhou, Y., 2019. **PaCTS 1.0: A Crowdsourced Reporting Standard for Paleoclimate Data.** Paleoceanography and Paleoclimatology 34, 1570--1596. <https://doi.org/10.1029/2019pa003632>
:::
