---
title: 'Get Engaged'
---


# Various ways to get involved

<!-- Putting in a link use [] for the actual link and then () for the text the link applies to -->

The OneGeochemistry initiative is a voluntary effort supported by a part time funded coordinator and only works with through the involvement of the community, your involvement.

Involvement has many forms from spamming ideas and reviewing those to board membership and decision making processes.

As OneGeochemistry is still developing the community is encouraged to help set up its formal governance, legal structure, technical and scientific expert committees and membership form.

## Conference Interactions

The current OneGeochemistry initiative members are actively organising research data sessions, town hall meetings and occasionally host a booth at international conferences such as EGU General Assembly, Goldschmidt and AGU Fall Meeting. It is easy to get in touch with any of us there, please come over for a chat about the initiative.

-   EGU General Assembly 2023, Vienna (23 April - 28 April)

    -   Town Hall Meeting on Monday 24 April 2023 (Monday, 19.00, Rm 0.96) (link: )

    -   Session XY with talks xyz

-   Goldschmidt 2023, Lyon (9 July - 14 July)

    -   Session XY with talks zyz)

    -   

## Slack Work Space and Email

Join our Slack workspace (https://join.slack.com/t/onegeochemistry/shared_invite/zt-18gjyj49u-FRf1XwCU1vj8xxCEUYoD7Q) for ad-hoc updates and requests from the organisation, it is an open platform where you can share ideas and suggestions. This is the place for low latency messaging and rapid sharing of resources.

## We'll share some info on such and such basis, these are the channels, actively ask people to share the initiative's imperative

Contributions

-   

## Become a Member

Becoming a member is the lightweight option with which you will receive updates via a mailing list and are actively encouraged to share your ideas about the best way to make geochemical data and resources more interoperable across the globe.

Being a member you can make yourself electable for the board, join or lead scientific and technical expert committees to advise on and help coordinate development of standard data reporting methods, method specific vocabularies, as well as metadata profiles.

## Become a Partner

Data infrastructure organisations, or groups as well as laboratories and institutes can become OneGeochemistry partner and contribute via a representative member of their organisation to the OneGeochemistry mission.

Making geochemical data more standardised and interoperable between institutions and nations **creating a global network of geochemical data resources**.

## Contact the Coordinator

Get in touch with the current OneGeochemistry coordinator on [onegeochemistry\@codata.org](#0)