# Overview

## Introduction
The OneGeochemistry CODATA Working Group’s mission is to advance geoscientific knowledge and discoveries by building and maintaining consensus-driven standards that make geochemistry research data globally findable and accessible, and truly interoperable and reusable to both humans and machines.

- OneGeochemistry seeks to create a global geochemical data network that facilitates and promotes discovery of, and access to, geochemical data through coordination and collaboration among international geochemical data providers by:

- Engaging global communities to create and maintain international standards, vocabularies and best practice documents for geochemical techniques and analytes;

- Publishing these community-agreed standards, vocabularies and best practices in a format that makes geochemical data globally FAIR and enables direct access and interpretation by machines for computational analysis and modelling; and

- Providing standards and best practice guidelines to record provenance, methodology and a measure of data quality that will enable users to trust, interpret and reuse data.

## Rationale
Geochemical data have applications in many disciplines including geology, cosmology, environment, resources (groundwater, minerals, energy), geohealth, ocean and agriculture. As such, geochemical data play an important role in at least six of the United Nations Sustainable Development Goals. To support these disciplines and goals, there is a growing need to provide advice and support the implementation of data quality assurance/quality control (QA/QC) validation methods for laboratories, repositories, publishers and policy makers. When provenance, methodology and a measure of data quality are consistently documented others will be enabled to trust, interpret and reuse data. In enabling and simplifying the (re)use of geochemical data, OneGeochemistry will help to facilitate acceleration of the generation of new geoscientific knowledge and discoveries.
As OneGeochemistry organises collaboration and coordination of data reporting standardisation efforts that are non-unique across the diverse geochemistry communities, this initiative fills a niche previously unoccupied. Standardisation efforts have always focused on national, programmatic or less centralised levels. The formalisation of OneGeochemistry and endorsement by societies and associations will enable the initiative to develop and promote influential, community-driven data conventions and best practices necessary to build a global network of high-quality, trusted geochemical data. These actions will enable FAIRer geochemical data, simplifying data (re)use which will both contribute to many UN Sustainable Development goals and accelerate the generation of new geoscientific knowledge and discoveries.

## Work Plan
During the two years as CODATA Working Group, OneGeochemistry will focus on Community Building (engaging with partners and participants, forming expert working groups, and  expanding efforts to seek endorsement of unions, societies, commissions and associations; in especially the first half year of WG formation), Generation of Common Vocabularies (through formation of expert working groups and collaboration between existing initiatives) and Generation of FIPs and Recommendations (of  geochemistry data reporting). The OneGeochemistry Initiative has sent out a formal letter seeking endorsement to several geochemical associations, commissions and societies. Once endorsed by these societies OneGeochemistry will extend an invitation to experts from these and the wider geochemistry community to join expert groups in early 2023. One expert group will be charged to develop common vocabularies and another expert group will where possible build upon existing or else generate new recommendations towards geochemical data reporting. Firstly, common vocabularies for both geochemical techniques and analytes will be created by the geochemistry community (e.g. for XRF and ICP-MS, elemental concentrations and U–Pb isotopes). These vocabularies will be developed in consultation and collaboration with other initiatives and groups that are well advanced in the development of digital data standards that both ensure compliance with FAIR and also enable interoperability of geochemical data with the other 10 Work Packages of the WorldFAIR project. These initiatives and groups include the International Union of Pure and Applied Chemistry (IUPAC) and their ‘Colour Books’; CODATA DDI-CDI Cross Domain Integration Initiative; the CODATA Digital Representation of Units of Measure (DRUM) Task Group; and relevant Research Data Alliance (RDA) groups (e.g., Vocabulary Services Interest Group; Earth, Space, and Environmental Sciences Interest Group; etc): these efforts will be aligned with the ‘10 Simple Rules’ for making a vocabulary FAIR. These FAIR vocabularies are to be published through Research Vocabularies Australia (RVA) and will serve as examples on how to build and publish further geochemistry subdiscipline specific vocabularies.
Through the CODATA Working Group, and as part of the CODATA-led WorldFAIR Project, OneGeochemistry aims to engage and motivate community repositories and databases to share their FAIR Enabling Resources (FERs) in a FAIR Implementation Profile (FIP). From the various FIPs, common FERs can be extracted to be published (after about a year into the WG) that will help repositories and databases to become more FAIR (especially facilitating interoperability). The publication of vocabularies, FIPs and geochemistry data reporting recommendations will allow the community to use and consider them for QA/QC of geochemical datasets published in the literature.
Although this Working Group has been established in the context of the WorldFAIR Project and the process of formalising OneGeochemistry in that project, it will continue beyond the life of the WorldFAIR project, ensuring continuity and sustainability in the process of building the OneGeochemistry initiative.